name: example

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: send notification
        uses:  guyzsarun/line-notify-action@a83da35b008cb235b1e7dab5fde2753c2543ee66
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          message: "hello world"
