name: example

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: send notification
        uses:  guyzsarun/line-notify-action@845812915a10e1a10d1b113acca9495b67eb419c
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          message: "hello world"
