name: example

on:
  workflow_dispatch:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: send notification
        uses:  ./
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          message: "hello world"
